### ISSUE TITLE
Add opportunities page to nav + make nav links more flexible

### ISSUE THREAD

**Issue by M0nica** [M0nica/ambition-fund-website#11]
There is a list of free and low-cost professional development opportunities at: http://localhost:8000/opportunities or /opportunities. However, this page needs to be added to the Navigation component. The current navigation component doesn't work on the opportunities page due to the anchor links (throws error in dev and fails "silently" in production). 

Tasks to be completed
- [ ] Make the navigation on the /opportunities page functional
- [ ]  Add link to the /opportunities page in the sitewide navigation

**Comment by jordan-paz** [comment]
I can take care of this ✋ 😃

**Comment by M0nica** [comment]
Great, I just assigned this to you @jordan-paz!
