### ISSUE TITLE
[Increase Test Coverage] Navigation

### ISSUE THREAD

**Issue by M0nica** [M0nica/ambition-fund-website#16]
- jest/react-testing-library unit tests should be added to the nav component to confirm that the link to homepage, mission and opportunities appear as expected.
- this functionality should be tested both within the context of the index page and non-index page (i.e., testing https://github.com/M0nica/ambition-fund-website/blob/2d388b90541c4493423e6285ed3285d7ae5e8261/src/components/common/navigation/navigation.js#L54)

**Comment by jordan-paz** [comment]
I can take this one ✋ 😃
