### ISSUE TITLE
Add Hover State to - Receive Updates Button

### ISSUE THREAD

**Issue by M0nica** [M0nica/ambition-fund-website#4]
The receive updates button currently doesn't have a hover state but should be updated to appear different on hover. Also, the link in the button should no longer have an underline (regardless of hover state). 

<img width="365" alt="Screen Shot 2020-06-21 at 12 12 38 AM" src="https://user-images.githubusercontent.com/6998954/85216569-f8707b00-b353-11ea-8068-ffb9d3c16784.png">

**Comment by omaratta212** [comment]
Hello 👋🏼 , I can work on this if contributions are allowed!

**Comment by M0nica** [comment]
Hi @omaratta212, thank you for your interest in contributing. Feel free to work on this issue and let me know if you have any questions!
