### ISSUE TITLE
Align Icon with Site Title

### ISSUE THREAD

**Issue by M0nica** [M0nica/ambition-fund-website#5]
In the site navigation the icon is raised to the left of the text "Ambition Fund". The icon and site title should appear to be aligned to the same axis so that one is not higher or lower than the other. 
<img width="220" alt="Screen Shot 2020-06-21 at 6 59 03 AM" src="https://user-images.githubusercontent.com/6998954/85222951-d9420f80-b38c-11ea-99c9-894443cc992b.png">

**Comment by jordan-paz** [comment]
I can take this one 😄

**Comment by M0nica** [comment]
@jordan-paz Great, I am looking forward to your contribution. Please let me know if you have any questions.
